
INSERT INTO candidates (name, years_experience, skills) VALUES ('Micheal VonRueden', 9, '["Safety Compliance","Operations","Logistics","Lean Manufacturing","Team Leadership"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Joanne Treutel', 5, '["Logistics","Safety Compliance","Operations","Maintenance","Team Leadership","Lean Manufacturing"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Randal Lehner', 4, '["Sustainability","Logistics","Safety Compliance","Operations","Maintenance"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Miss Felicia Hegmann', 2, '["Lean Manufacturing","Logistics","Operations","Safety Compliance","Maintenance","Team Leadership","Sustainability"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Miranda Will', 14, '["Safety Compliance","Operations","Team Leadership","Maintenance","Sustainability","Logistics","Lean Manufacturing"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Brett Rodriguez', 12, '["Maintenance","Operations","Team Leadership","Sustainability","Safety Compliance","Logistics"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Leon Flatley-Ankunding', 19, '["Maintenance","Team Leadership","Logistics","Safety Compliance","Operations"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Stephanie Douglas', 2, '["Safety Compliance","Logistics","Sustainability","Lean Manufacturing","Maintenance"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Miss Ethel Jerde', 2, '["Team Leadership","Sustainability","Operations","Lean Manufacturing","Safety Compliance","Maintenance","Logistics"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Norma McClure', 10, '["Sustainability","Operations","Team Leadership","Safety Compliance","Logistics","Maintenance","Lean Manufacturing"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Anita Kemmer', 2, '["Team Leadership","Logistics","Safety Compliance","Operations","Lean Manufacturing","Sustainability","Maintenance"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Dean Ankunding', 5, '["Team Leadership","Operations","Safety Compliance","Maintenance","Sustainability"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Genevieve King DVM', 12, '["Lean Manufacturing","Operations","Team Leadership","Sustainability","Logistics","Safety Compliance"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Irene Brekke', 14, '["Team Leadership","Operations","Safety Compliance","Maintenance","Sustainability","Logistics","Lean Manufacturing"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Mr. Dominic Collier DVM', 6, '["Safety Compliance","Maintenance","Team Leadership","Sustainability","Logistics","Operations","Lean Manufacturing"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Brandon Jerde', 10, '["Maintenance","Operations","Logistics","Lean Manufacturing","Team Leadership"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Evelyn Daniel', 8, '["Lean Manufacturing","Team Leadership","Maintenance","Operations","Safety Compliance","Logistics","Sustainability"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Yvonne Dare', 18, '["Sustainability","Operations","Lean Manufacturing","Logistics","Team Leadership","Maintenance","Safety Compliance"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Randolph Roberts', 18, '["Maintenance","Operations","Logistics","Lean Manufacturing","Team Leadership","Sustainability","Safety Compliance"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Alyssa Flatley', 7, '["Maintenance","Safety Compliance","Team Leadership","Logistics","Sustainability"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Danny Lesch DVM', 10, '["Maintenance","Team Leadership","Operations","Sustainability","Safety Compliance"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Caleb Ziemann DDS', 4, '["Sustainability","Logistics","Team Leadership","Safety Compliance","Operations","Maintenance"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Lana Hermann', 16, '["Sustainability","Operations","Logistics","Team Leadership","Maintenance","Lean Manufacturing"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Mr. Karl Wisoky', 6, '["Maintenance","Operations","Team Leadership","Logistics","Lean Manufacturing"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Mr. Dwayne Howe', 4, '["Team Leadership","Sustainability","Safety Compliance","Operations","Lean Manufacturing","Maintenance","Logistics"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Latoya Lakin', 20, '["Logistics","Operations","Maintenance","Lean Manufacturing","Safety Compliance","Sustainability","Team Leadership"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Daryl Kuhn', 4, '["Team Leadership","Logistics","Sustainability","Lean Manufacturing","Safety Compliance","Operations","Maintenance"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Mr. Dustin McLaughlin', 20, '["Sustainability","Team Leadership","Lean Manufacturing","Operations","Safety Compliance"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Cornelius Murazik', 3, '["Logistics","Safety Compliance","Maintenance","Operations","Team Leadership"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Cheryl Rau', 18, '["Team Leadership","Sustainability","Safety Compliance","Logistics","Maintenance"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Anne Stehr', 5, '["Maintenance","Safety Compliance","Logistics","Operations","Sustainability","Lean Manufacturing","Team Leadership"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Fred Runolfsdottir', 18, '["Safety Compliance","Lean Manufacturing","Sustainability","Maintenance","Team Leadership"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Jeff Durgan', 17, '["Sustainability","Operations","Team Leadership","Maintenance","Lean Manufacturing","Logistics","Safety Compliance"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Johnnie Hermiston', 15, '["Lean Manufacturing","Safety Compliance","Team Leadership","Operations","Sustainability","Logistics","Maintenance"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Shannon Kutch', 4, '["Lean Manufacturing","Maintenance","Safety Compliance","Sustainability","Operations","Logistics","Team Leadership"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Marco Rau', 11, '["Sustainability","Team Leadership","Lean Manufacturing","Operations","Safety Compliance"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Michelle Hirthe', 16, '["Team Leadership","Logistics","Safety Compliance","Lean Manufacturing","Maintenance","Operations","Sustainability"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Brittany Jast DDS', 11, '["Logistics","Maintenance","Operations","Safety Compliance","Lean Manufacturing","Team Leadership","Sustainability"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Sarah Jones', 8, '["Operations","Logistics","Lean Manufacturing","Maintenance","Team Leadership","Safety Compliance"]');
INSERT INTO candidates (name, years_experience, skills) VALUES ('Seth Fahey', 11, '["Sustainability","Operations","Safety Compliance","Team Leadership","Lean Manufacturing","Maintenance"]');

INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (1, 81.4, 53.6, 84.6);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (2, 45.7, 53.4, 59.6);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (3, 45.1, 58.9, 62.6);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (4, 42, 44.6, 77.5);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (5, 73.1, 54.5, 94.3);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (6, 50.9, 58.5, 85.4);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (7, 66.2, 62.1, 95.1);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (8, 81.7, 95.4, 95.4);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (9, 62.5, 59.2, 62.3);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (10, 63.1, 89.9, 64.6);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (11, 49.1, 73.8, 69.7);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (12, 75.4, 60.2, 73.8);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (13, 85.5, 94.6, 89.8);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (14, 58.2, 96.1, 73.1);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (15, 76.1, 69.9, 78);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (16, 42.9, 69, 82.7);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (17, 95.5, 40.7, 69.4);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (18, 48, 66.8, 95.5);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (19, 92.9, 41.2, 71.8);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (20, 61.7, 73.7, 75.8);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (21, 78.3, 83.8, 78.2);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (22, 75.9, 40.4, 71.6);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (23, 81.6, 43, 89.2);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (24, 74.4, 84.1, 79.9);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (25, 86.8, 64.1, 86.3);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (26, 47.4, 43.5, 47);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (27, 69.6, 51.8, 70.5);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (28, 61.8, 50.6, 89.9);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (29, 76.8, 60.1, 62);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (30, 82.3, 66, 62.7);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (31, 62.4, 56, 67.9);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (32, 65.4, 42.3, 68.9);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (33, 55.9, 43.8, 98.5);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (34, 48.4, 71.6, 46.9);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (35, 87.2, 47.8, 91.7);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (36, 72.9, 54.1, 86.8);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (37, 60.5, 50.7, 70.2);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (38, 73.6, 62.3, 94.1);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (39, 92.5, 62.7, 79.8);
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score) VALUES (40, 86.8, 56.3, 54.1);

